name: Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ai-agent:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-agent:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Stop and remove old container if exists
          docker stop ai-agent || true
          docker rm ai-agent || true

          # Pull latest image
          docker pull ${{ secrets.DOCKER_USERNAME }}/ai-agent:latest

          # Run new container with env file
          docker run -d -p 80:5000 \
            --env-file /home/ubuntu/.env \
            --name ai-agent \
            ${{ secrets.DOCKER_USERNAME }}/ai-agent:latest
